### ISSUE TITLE
Misspelled loginValid

### ISSUE THREAD

**Issue by seanc** [adonisjs/legacy-documentation#1]
http://adonisjs.com/docs/3.0/authentication#loginviaid-id-

Just a small spelling mistake there

**Comment by RomainLanz** [comment]
Dear @seanc,

Could you made a Pull Request with changes?

Thanks for your contribution!

**Comment by seanc** [comment]
I apologize, didn't realize it was `loginViaId` D:

**Comment by RomainLanz** [comment]
Maybe it should be a good idea to rename this method to `loginWith`. 🤔

What do you think @thetutlage ?

**Comment by thetutlage** [comment]
`loginViaId` is good 😄
