### ISSUE TITLE
Error when "npm run setup"

### ISSUE THREAD

**Issue by dexmendonca** [adonisjs/legacy-documentation#15]
Hi 😄 , Can you help me?
This appears later when you are going to compile the docs:

adonis-app@3.0.0 setup:3.1 /home/myuser/tests/adonis-documentation
> ./ace build:docs adonisjs/docs --docVersion=3.1 --branch=3.1 --parser=adoc

Cloning into '/home/myuser/tests/adonis-documentation/node_modules/docketjs/tmp'...
TypeError: Cannot read property 'join' of null

> adonis-app@3.0.0 setup:3.2 /home/myuser/tests/adonis-documentation
> ./ace build:docs adonisjs/docs --docVersion=3.2 --branch=3.2 --parser=adoc

Cloning into '/home/myuser/tests/adonis-documentation/node_modules/docketjs/tmp'...
TypeError: Cannot read property 'join' of null

Thanks 👍

**Comment by thetutlage** [comment]
The docs have been moved to https://github.com/adonisjs/adonisjs.com with better build process
