### ISSUE TITLE
Can't find the meaning of the 'confirmed' rule in validation

### ISSUE THREAD

**Issue by lmj0011** [adonisjs/legacy-documentation#16]
in the first diagram here: http://adonisjs.com/docs/3.2/validator#_basic_example
what does `confirmed` mean at the line with `password: 'required|confirmed'`?

The Indicative docs don't even mention it.
http://indicative.adonisjs.com/#indicative-schema-rules

**Comment by thetutlage** [comment]
Their should be a field called `password_confirmation` with same text as `password`.  Feel free to check source code

https://github.com/poppinss/indicative/blob/develop/src/Validations/index.js#L45

**Comment by lmj0011** [comment]
Is that suppose to be common knowledge? I wouldn't have figured that out.

**Comment by thetutlage** [comment]
Checking source code is never a bad idea, since you can explore more hidden features.

Also it is hard for me to make sure each point is documented, sometimes things just skip over my head. If you find missing pieces, always feel free to create a PR, so that everyone else can benefit from same
