### ISSUE TITLE
withTrashed() method needs documentation

### ISSUE THREAD

**Issue by lmj0011** [adonisjs/legacy-documentation#17]
https://github.com/adonisjs/adonis-lucid/blob/develop/src/Lucid/QueryBuilder/methods.js#L213

http://adonisjs.com/docs/3.2/lucid#_lucid_methods

see for context: https://gitter.im/adonisjs/adonis-framework?at=58e20f028fcce56b20c506c4

**Comment by thetutlage** [comment]
Mind creating a PR?

**Comment by lmj0011** [comment]
yea, when I get a break

**Comment by thetutlage** [comment]
Documented
