### ISSUE TITLE
Add more documentation on Traits

### ISSUE THREAD

**Issue by watzon** [adonisjs/legacy-documentation#24]
There seem to be a few holes in the docs, one of which is Traits. They are mentioned briefly [here](http://adonisjs.com/docs/3.2/lucid#_traits), but after reading about traits I feel like I should know what they are and how to use them/add my own. I'd be happy to write up the documentation and make a pull request, but first I need to know how traits work in Adonis, what built-in traits there are (if any), etc.

**Comment by thetutlage** [comment]
@watzon Yup I agree that docs are not as they should be. I am working on the newer release and planning to improve docs too.

**Comment by tomerof** [comment]
So how do i create a new trait?
i tried and got this error E_INVALID_MODEL_TRAIT: Make sure you have defined register method on model

**Comment by thetutlage** [comment]
Documented here http://dev.adonisjs.com/docs/4.0/traits
