### ISSUE TITLE
JWT authentication current logged in user access

### ISSUE THREAD

**Issue by abdoolly** [adonisjs/legacy-documentation#25]
The documentation says that the currently logged in user should be accessed by 
`request.currentUser`
only for session based authentication.
and any other authentication by 
`request.authUser`

when i tried using the JWT authentication the user was accessed only by
`request.currentUser`

just wanted to help I find this framework is very good and i wanted to be better 
thanks for that great framework.

**Comment by thetutlage** [comment]
Sure
