### ISSUE TITLE
Grammar in footer

### ISSUE THREAD

**Issue by chipit24** [adonisjs/legacy-documentation#26]
The footer of http://dev.adonisjs.com/docs contains the phrase "Developer by Harminder Virk". This should be "Develope**d** by Harminder Virk".

I can create a PR for this change, but I'm not sure which branch to base this off of.

**Comment by thetutlage** [comment]
It will go here https://github.com/adonisjs/adonisjs.com inside `develop` branch

**Comment by thetutlage** [comment]
Closing since fixed
