### ISSUE TITLE
handling validation failure section

### ISSUE THREAD

**Issue by protzi** [adonisjs/legacy-documentation#28]
https://dev.adonisjs.com/docs/4.0/validator#_handling_validation_failure
`return this.ctx.response(errorMessages)`
should be  ?
` return this.ctx.response.send(errorMessages)`

**Comment by thetutlage** [comment]
Yup, mind creating a PR for same?

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/docs/commit/b9b5bf432ff92f3563c8cf5d29ae01be078ddcd4
