### ISSUE TITLE
Mail.raw shows wrong number of arguments

### ISSUE THREAD

**Issue by dustinboss** [adonisjs/legacy-documentation#31]
Hi. I’m on Adonis 4.0.23, and in the Adonis 4 docks, it says that the `Mail.raw` method accepts three arguments, but the actual code only accepts two arguments.

Docs:
http://dev.adonisjs.com/docs/4.0/mail#_raw_string_data_callback

Code:
https://github.com/adonisjs/adonis-mail/blob/2674536d59f5c033569f40b558ac394317033e21/src/Mail/Sender.js#L150

Thanks!

**Comment by jacekk** [comment]
I updated docs in https://github.com/adonisjs/docs/pull/172 .
