### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by akusany2** [adonisjs/legacy-documentation#36]
Hi, I was going through the docs and found a weird syntax:

```
Route
  .resource('users', 'UsersController')
  .middleware(new Map([
    ['auth']: ['users.store', 'users.update', 'users.delete']
  ]))
```

Why are we defining a property inside an array?

[Routing - Resource Middleware](https://adonisjs.com/docs/4.0/routing#_resource_middleware)

Pretty neat docs BTW!

**Comment by thetutlage** [comment]
That's how [ES6 Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Relation_with_Array_objects) works

and just @RomainLanz mentioned, there is a typo too. He will send a PR for same
