### ISSUE TITLE
JWT --option-- documentation missing in version 4.0

### ISSUE THREAD

**Issue by Malak67** [adonisjs/legacy-documentation#37]
Hi,

I have noticed that in the official documentation for version 4.0, the options part of the JWT Authentication is missing.
In version 3.2 it is still present.

This is extremely important as in version 4.0 there is no way of seeing how to add an expiry date for the JWT token whereas in 3.2 is clearly in the options object.

Please see bellow the screenshots:
version3.2 (it exsists):
![image](https://user-images.githubusercontent.com/9773044/33932148-d9937a36-dffa-11e7-83c6-e6d5eef4a1fa.png)
version 4.0 (not anymore):
![image](https://user-images.githubusercontent.com/9773044/33932189-f33b9496-dffa-11e7-9940-c136b357923d.png)

Is this intended?

Thanks,

Florin

**Comment by thetutlage** [comment]
Nope, would you mind sharing a PR for same inside https://github.com/adonisjs/docs repo?

**Comment by Malak67** [comment]
Hey,


I did a PR and changed the doc accordingly.


Can you please check and let me know if it`s ok.


Thanks,


Florin

________________________________

**Comment by thetutlage** [comment]
Closing in favor of related PR https://github.com/adonisjs/docs/pull/233
